package com.brokerage.dto;

import com.brokerage.model.User;

public class LoginResponse {
    
    private String token;
    private String username;
    private String role;
    private String customerId;
    
    public LoginResponse() {}
    
    public LoginResponse(String token, User user) {
        this.token = token;
        this.username = user.getUsername();
        this.role = user.getRole().name();
        this.customerId = user.getCustomerId();
    }
    
    // Getters and Setters ( this is auto-generated by IntelliJ IDEA, just wanted to point out :))
    public String getToken() {
        return token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getRole() {
        return role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    
    public String getCustomerId() {
        return customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
} 